apiVersion: v1
kind: Service
metadata:
  name: litecoin
  labels:
    app: litecoin
spec:
  ports:
  - port: 9332
    targetPort: 9332
  - port: 9333
    targetPort: 9333
  - port: 19332
    targetPort: 19332
  - port: 19333
    targetPort: 19333
  - port: 19444
    targetPort: 19444
  selector:
    app: litecoin
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: litecoin
spec:
  serviceName: "litecoin"
  replicas: 2
  selector:
    matchLabels:
      app: litecoin
  template:
    metadata:
      labels:
        app: litecoin
    spec:
      containers:
      - name: litecoin
        image: 0881XXXXXX.dkr.ecr.eu-west-1.amazonaws.com/stuff/litecoin:0.18.1
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 9332
          name: port-9332
        - containerPort: 9333
          name: port-9333
        - containerPort: 19332
          name: port-19332
        - containerPort: 19333
          name: port-19333
        - containerPort: 19444
          name: port-19444
        volumeMounts:
        - name: data
          mountPath: /home/litecoin/.litecoin
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
