apiVersion: v1
kind: Service
metadata:
  name: litecoin
  labels:
    app: litecoin
spec:
  ports:
  - port: {{ .Values.service.externalPort1 }}
    targetPort: {{ .Values.service.internalPort1 }}
  - port: {{ .Values.service.externalPort2 }}
    targetPort: {{ .Values.service.internalPort2 }}
  - port: {{ .Values.service.externalPort3 }}
    targetPort: {{ .Values.service.internalPort3 }}
  - port: {{ .Values.service.externalPort4 }}
    targetPort: {{ .Values.service.internalPort4 }}
  - port: {{ .Values.service.externalPort5 }}
    targetPort: {{ .Values.service.internalPort5 }}
  selector:
    app: litecoin
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: litecoin
spec:
  serviceName: "litecoin"
  replicas: {{ .Values.statefulSet.replicas }}
  selector:
    matchLabels:
      app: litecoin
  template:
    metadata:
      labels:
        app: litecoin
    spec:
      restartPolicy: Always
      imagePullSecrets:
      - name: {{ .Values.statefulSet.imagePullSecrets }}
      containers:
      - name: {{ .Values.statefulSet.containerName }}
        image: {{ .Values.statefulSet.image }}:{{ .Values.statefulSet.tag }}
        imagePullPolicy: {{ .Values.statefulSet.pullPolicy }}
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: {{ .Values.statefulSet.containerPort1 }}
          name: {{ .Values.statefulSet.containerPortName1 }}
        - containerPort: {{ .Values.statefulSet.containerPort2 }}
          name: {{ .Values.statefulSet.containerPortName2 }}
        - containerPort: {{ .Values.statefulSet.containerPort3 }}
          name: {{ .Values.statefulSet.containerPortName3 }}
        - containerPort: {{ .Values.statefulSet.containerPort4 }}
          name: {{ .Values.statefulSet.containerPortName4 }}
        - containerPort: {{ .Values.statefulSet.containerPort5 }}
          name: {{ .Values.statefulSet.containerPortName5 }}
        volumeMounts:
        - name: data
          mountPath: /home/litecoin/.litecoin
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
