service:
  externalPort1: 9332
  internalPort1: 9332
  externalPort2: 9333
  internalPort2: 9333
  externalPort3: 19332
  internalPort3: 19332
  externalPort4: 19333
  internalPort4: 19333
  externalPort5: 19444
  internalPort5: 19444
statefulset:
  containerName: litecoin
  replicas: 2
  image: 0881XXXXXX.dkr.ecr.eu-west-1.amazonaws.com/stuff/litecoin
  tag: 0.18.1
  pullPolicy: Always
  containerPort1: 9332
  containerPortName1: port-9332
  imagePullSecrets: <<vault>>
