service:
  externalPort1: 9332
  internalPort1: 9332
  externalPort2: 9333
  internalPort2: 9333
  externalPort3: 19332
  internalPort3: 19332
  externalPort4: 19333
  internalPort4: 19333
  externalPort5: 19444
  internalPort5: 19444
statefulSet:
  containerName: litecoin
  replicas: 4
  image: 0881XXXXXX.dkr.ecr.eu-west-1.amazonaws.com/stuff/litecoin
  tag: 0.18.1
  pullPolicy: Always
  containerPort1: 9332
  containerPortName1: port-9332
  containerPort2: 9333
  containerPortName2: port-9333
  containerPort3: 19332
  containerPortName3: port-19332
  containerPort4: 19333
  containerPortName4: port-19333
  containerPort4: 19444
  containerPortName4: port-19444
  imagePullSecrets: <<vault>>
